### ISSUE TITLE
Move class TeamdynamixApi to app/services

### ISSUE THREAD

**Issue by edestecd** [MiamiOH/foreman_teamdynamix#17]
Example: https://github.com/theforeman/puppetdb_foreman/blob/master/app/services/puppetdb.rb

This seems better than using lib

**Comment by nipendar** [comment]
estimate 2 hours

**Comment by nipendar** [comment]
adding work item to use webmock to mock HTTP calls. 

New estimate: 4 hours

**Comment by edestecd** [comment]
Does this add a gem dependency?
OR does Foreman Core already use this?

**Comment by nipendar** [comment]
this would add a development dependency for webmock. If we don't use webmock user will have to set correct api credentials and tests will create assets in the corresponding Teamdynamix account

**Comment by nipendar** [comment]
@edestecd can you please close this

**Comment by edestecd** [comment]
Resolved by #21
