### ISSUE TITLE
Show TD fields and link to same Asset in TD

### ISSUE THREAD

**Issue by edestecd** [MiamiOH/foreman_teamdynamix#4]

**Comment by nipendar** [comment]
please validate
- User should be able to click on one or more attributes(asset id, name etc) from the TD asset pane in foreman hosts
- the link should open a new tab to display the asset in TeamDynamix

**Comment by edestecd** [comment]
I think we want to show these fields initially:
Owner
Parent Asset
mu.ci.Description
Ticket Routing Details
Asset ID

**Comment by edestecd** [comment]
However the fields shown should be read in from a configurable yaml file.

**Comment by nipendar** [comment]
@edestecd 
These are the four Owner related attributes of an Asset:
    "OwningCustomerID": UUID,
    "OwningCustomerName": "a person's name",
    "OwningDepartmentID": Integer_Dept_ID,
    "OwningDepartmentName": Dept_Name

Any of these can be configured via yaml as: 'Owner': OwningDepartmentID

**Comment by nipendar** [comment]
mostly done. 2 hours if there is only minor changes post PR review

**Comment by edestecd** [comment]
Resolved via #18
