### ISSUE TITLE
Create TD Asset when Host is created in Foreman

### ISSUE THREAD

**Issue by edestecd** [MiamiOH/foreman_teamdynamix#5]
Use the TD api and read username/password from yaml file.

**Comment by nipendar** [comment]
Definition
- Override hosts#create to also create an asset in TD via its REST API
- TD API credentials appId to be read from a yaml file
Comments
- Create REST call takes a TD asset as input, only one attribute 'status' is required.
- Define Error case, if create call fails, what feedback do we want on UI?
- We should talk about what all attributes we would want to POST. see https://api.teamdynamix.com/TDWebApi/Home/type/TeamDynamix.Api.Assets.Asset

**Comment by edestecd** [comment]
Rails has after hooks for create to do such things: http://guides.rubyonrails.org/active_record_callbacks.html

**Comment by edestecd** [comment]
We want to store the fqdn or a uniqueid in TD so a urll can be generated back to foreman.
We also want to create a new field for hosts in Foreman to store the Asset uniqueid in TeamDynamix so we can reference the TD asset later for display etc.

**Comment by nipendar** [comment]
1. We want to store the fqdn or a uniqueid in TD so a url can be generated back to foreman.
- saved as Serial number and Name field
2. new field added as td_asset_id
