### ISSUE TITLE
Mark Asset as retired in TeamDynamix upon Host deletion

### ISSUE THREAD

**Issue by edestecd** [MiamiOH/foreman_teamdynamix#7]

**Comment by edestecd** [comment]
When a Host is deleted in Foreman it should mark the matching asset in TD as Retired.

**Comment by edestecd** [comment]
Rails has after hooks for delete to do such things: http://guides.rubyonrails.org/active_record_callbacks.html

Delete in Foreman should fail if not successfully marked as retired in TD

**Comment by nipendar** [comment]
some work already done.
estimate 2-4 hours for getting it reviewed, follow up commits

**Comment by edestecd** [comment]
Solved by #19
